Separate DB per Jest Worker (Fixes #272)
shelfio/jest-mongodb pull request #304
Opened 2021-09-20 13:16 UTC by Siloss

2021-09-20 13:18 UTC, vladgolubev commented
Could you please rename the variable to `useSharedDBForAllJestWorkers`?

2021-09-20 13:22 UTC, randomhash requested changes
```suggestion
To use separate database for each jest worker pass the `useSharedDBForAllJestWorkers: false` (doesn't create `process.env` variable when using this option):
```

2021-09-20 13:22 UTC, randomhash commented on readme.md
> +To use separate database for each jest worker pass the `separateMongoInstances: true` (doesn't create `process.env` variable when using this option):
```suggestion
```suggestion
To use a separate database for each jest worker pass the `useSharedDBForAllJestWorkers: false` (doesn't create `process.env` variable when using this option):
```

```

2021-09-20 13:22 UTC, randomhash commented on helpers.js
> +    const {separateMongoInstances} = require(resolve(cwd, 'jest-mongodb-config.js'));
please update logic of the variable here

2021-09-21 11:01 UTC, vladgolubev approved these changes

2021-09-21 11:01 UTC, merged